language: python

# Workaround for Python 3.7 on Travis CI, also see:
# https://github.com/travis-ci/travis-ci/issues/9069#issuecomment-425720905
dist: xenial
sudo: yes

python:
- "3.4"
- "3.5"
- "3.6"
- "3.7"

install: pip install -U tox-travis

script: tox
